name: neuralop
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - adam=1.0.1=hdfd78af_0
  - arrow-cpp=21.0.0=hac1acdb_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313hf0014fa_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.2=pyhd8ed1ab_1
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.14=py313h46c70d0_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.5.0=h6a678d5_1
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.3.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcurl=8.16.0=heebcbe5_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.1.0=h767d61c_2
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.20=h4ab18f5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.22.0=hd8eb582_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py313ha5a4a6c_1
  - openjdk=21.0.6=h38aa4c6_0
  - openssl=3.5.0=h7b32b05_1
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h23c847b_0
  - pango=1.50.7=h668f713_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313h536fd9c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py4j=0.10.9.9=py313h06a4308_0
  - pyarrow=21.0.0=py313h23c847b_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyspark=4.0.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyzmq=27.0.0=py313h8e95178_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.2=h5eee18b_0
  - s2n=1.5.14=hdbd6064_0
  - setuptools=78.1.1=py313h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py313h536fd9c_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - annotated-types==0.7.0
      - asdfghjkl==0.1a4
      - attrs==25.3.0
      - backpack-for-pytorch==1.7.1
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - configmypy==0.2.0
      - contourpy==1.3.2
      - crc32c==2.7.1
      - curvlinops-for-pytorch==2.0.1
      - cycler==0.12.1
      - donfig==0.8.1.post1
      - einconv==0.1.0
      - einops==0.8.1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.14.0
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - laplace-torch==0.2.2.2
      - lightning-utilities==0.14.3
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - narwhals==1.43.0
      - nbformat==5.10.4
      - networkx==3.5
      - neuraloperator==1.0.2
      - numcodecs==0.16.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opt-einsum==3.4.0
      - pillow==11.2.1
      - plotly==6.1.2
      - pluggy==1.6.0
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pytest==8.4.0
      - pytest-mock==3.14.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.32.4
      - rpds-py==0.25.1
      - ruamel-yaml==0.18.14
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorly==0.9.0
      - tensorly-torch==0.5.0
      - threadpoolctl==3.6.0
      - torch==2.7.1
      - torch-harmonics==0.7.4
      - torchmetrics==1.7.3
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - typing-inspection==0.4.1
      - unfoldnd==0.2.3
      - urllib3==2.4.0
      - wandb==0.20.1
      - zarr==3.0.8
      - zencfg==0.3.0
prefix: /home/rusted/anaconda3/envs/neuralop
